config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'
  get '/activity' => 'visitors#activity',   as: :activity

  resources :highlights, only: %i(create update destroy)
  resources :users

  # Findings
  get   '/finding/:permalink'        => 'findings#show',   as: :finding
  patch '/finding/:permalink'        => 'findings#update'
  get   '/finding/:permalink/lock'   => 'findings#lock',   as: :lock_finding
  get   '/finding/:permalink/unlock' => 'findings#unlock', as: :unlock_finding

  # Follow / unfollow
  get '/follow/:id'              => 'followings#follow'
  get '/unfollow/:id'            => 'followings#unfollow'

  # Friend / unfriend
  get '/friend/:id'              => 'friendships#friend'
  get '/unfriend/:id'            => 'friendships#unfriend'

  # User settings
  get '/settings'                => 'users#settings'

  # OAuth failure (for all strategies)
  get '/auth/failure'            => 'sessions#failure'

  # Twitter authentication
  get '/signin'                  => 'sessions#new',     as: :signin
  get '/signout'                 => 'sessions#destroy', as: :signout
  get '/auth/twitter/callback'   => 'sessions#create'

  # Evernote connect
  get '/evernote/connect'        => 'evernote#new'
  get '/evernote/sync'           => 'evernote#sync',     as: :sync_evernote
  get '/auth/evernote/callback'  => 'evernote#create'

  # Facebook authentication
  get '/facebook/connect'        => 'facebook#new'
  get '/auth/facebook/callback'  => 'facebook#create'

  # Facebok messenger bot webook
  mount Messenger::Bot::Space    => "facebook/webhook"
end

app/views/layouts/_favicon.slim
- if Rails.env.development?
  = favicon_link_tag 'owl_favicon_2-green.ico'

- if Rails.env.staging?
  = favicon_link_tag 'owl_favicon_2-black.ico'

- if Rails.env.production?
  = favicon_link_tag 'owl_favicon_2-dark-grey.ico'

app/views/layouts/_footer.slim
footer
  .container
    .row
      .col-lg-8.col-lg-offset-2.col-md-10.col-md-offset-1
        p.copyright.text-muted Copyright © Nosko 2016

app/views/layouts/_messages.html.slim
- flash.each do |name, msg|
  - if msg.is_a?(String)
    - type = (name.to_s == 'notice') ? 'success' : 'danger'
    div class="alert alert-#{type}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, id: "flash_#{name}"

app/views/layouts/_navigation.html.slim
nav.navbar
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
    .collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-left
        li= link_to 'Home', root_path, class: 'navbar-brand'
        - if user_signed_in?
          li= link_to 'Inbox',        '#'
          li= link_to 'Users',        users_path
          li
            - count = ActivityLog.new(current_user).unreviewed.count
            = link_to activity_path do
              = 'Activity Log'
              - if count > 0 && url_for != '/activity'
                span.label.label-danger.label-notification.pull-right.small-left-margin= count
      ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          li.dropdown
            a#user-menu-dropdown.dropdown-toggle aria-expanded='true' aria-haspopup='true' data-toggle='dropdown' href='#'
              .icon-to-right
                .ion-icon.ion-android-arrow-dropdown
                .icon-text= current_user.name
            ul.dropdown-menu aria-labelledby='user-menu-dropdown'
              li: a         href="#{user_path(current_user)}"  My profile
              li: a         href="#{settings_path}"            Settings
              li.divider role="separator"
              li: a#signout href="#{signout_path}"             Sign out

        - else
          li= link_to 'Sign in', signin_path

app/views/layouts/application.slim
doctype html
html
  head
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title
      = content_for?(:title) ? yield(:title) : 'Nosko'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Nosko'}"
    = stylesheet_link_tag    'application', 'data-turbolinks-track' => true, media: 'all'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    == render 'layouts/favicon'

  body: .wrapper
    header
      == render 'layouts/navigation'
    main role='main'
      .container.body
        == render 'layouts/messages'
        = yield